// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7.2.2025, 09.26.26
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/Propelcom/test-vs-copilot/nuxt3-todo-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Propelcom/test-vs-copilot/nuxt3-todo-app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Propelcom/test-vs-copilot/nuxt3-todo-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Propelcom/test-vs-copilot/nuxt3-todo-app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Propelcom/test-vs-copilot/nuxt3-todo-app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Propelcom/test-vs-copilot/nuxt3-todo-app/plugins/**/*.{js,ts,mjs}","D:/Propelcom/test-vs-copilot/nuxt3-todo-app/composables/**/*.{js,ts,mjs}","D:/Propelcom/test-vs-copilot/nuxt3-todo-app/utils/**/*.{js,ts,mjs}","D:/Propelcom/test-vs-copilot/nuxt3-todo-app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Propelcom/test-vs-copilot/nuxt3-todo-app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Propelcom/test-vs-copilot/nuxt3-todo-app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;